"""Evidence-separated per-market research studies."""

from bot05.studies.contracts import (
    CONTROL_MARKETS,
    MFE_HORIZONS_MINUTES,
    PRIMARY_MARKETS,
    ExcursionHorizon,
    ExcursionObservation,
    ExperimentSpec,
    MarketRole,
    MarketStudyScope,
    SessionObservation,
    StudyConclusion,
    StudyContractError,
    StudyDataset,
    StudyPurpose,
    allowed_purposes,
    calculate_excursions,
    market_role,
)
from bot05.studies.metrics import (
    ExcursionMetrics,
    FunnelMetrics,
    MarketStudyMetrics,
    PerformanceMetrics,
    calculate_excursion_metrics,
    calculate_funnel,
    calculate_market_metrics,
    calculate_performance,
)
from bot05.studies.parity import (
    CandleParityMetrics,
    CandleParityPoint,
    CandleParityReport,
    ParityStatus,
    build_candle_parity_report,
    write_candle_parity_report,
)
from bot05.studies.reporting import (
    EvidenceAssessment,
    MarketStudyReport,
    assess_evidence,
    build_market_study_report,
    write_market_study_report,
)

__all__ = [
    "CONTROL_MARKETS",
    "CandleParityMetrics",
    "CandleParityPoint",
    "CandleParityReport",
    "MFE_HORIZONS_MINUTES",
    "PRIMARY_MARKETS",
    "ExcursionHorizon",
    "ExcursionObservation",
    "ExperimentSpec",
    "ExcursionMetrics",
    "EvidenceAssessment",
    "FunnelMetrics",
    "MarketRole",
    "MarketStudyMetrics",
    "MarketStudyReport",
    "MarketStudyScope",
    "SessionObservation",
    "StudyConclusion",
    "StudyContractError",
    "StudyDataset",
    "StudyPurpose",
    "PerformanceMetrics",
    "ParityStatus",
    "allowed_purposes",
    "assess_evidence",
    "build_market_study_report",
    "build_candle_parity_report",
    "calculate_excursions",
    "calculate_excursion_metrics",
    "calculate_funnel",
    "calculate_market_metrics",
    "calculate_performance",
    "market_role",
    "write_market_study_report",
    "write_candle_parity_report",
]
